/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio_tablero.logica.Interfaz;

import Ejercicio_tablero.logica.Tablero;

/**
 *
 * @author 66047656
 */
public class Principal extends javax.swing.JFrame {
public Tablero miTablero = new Tablero();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotonRestarLocal = new javax.swing.JToggleButton();
        BotonAñadirLocal = new javax.swing.JToggleButton();
        BotonAñadirVisitante = new javax.swing.JToggleButton();
        BotonRestarVisitante = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        BtnReiniciar = new javax.swing.JToggleButton();
        visitanteValor = new javax.swing.JLabel();
        localValor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("coso");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        BotonRestarLocal.setText("-");
        BotonRestarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestarLocalActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRestarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 30));

        BotonAñadirLocal.setText("+");
        BotonAñadirLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirLocalActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAñadirLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, 30));

        BotonAñadirVisitante.setText("+");
        BotonAñadirVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirVisitanteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAñadirVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 50, 30));

        BotonRestarVisitante.setText("-");
        BotonRestarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestarVisitanteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRestarVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 50, 30));

        jToggleButton5.setText("resultado");
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, -1));

        BtnReiniciar.setText("reiniciar");
        BtnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, -1));

        visitanteValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        visitanteValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visitanteValor.setText("0");
        visitanteValor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.add(visitanteValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 40, 30));

        localValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        localValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        localValor.setText("0");
        localValor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.add(localValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("visitante");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 40, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("local");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, -1));

        jLabel6.setText("Tablero");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReiniciarActionPerformed
     /*  Principal principal = new Principal();
       principal.setVisible(true);
       this.dispose(); */
     miTablero.reset();
     update();
    }//GEN-LAST:event_BtnReiniciarActionPerformed

    private void BotonAñadirLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirLocalActionPerformed
      miTablero.sumaLocal();
      update();
    }//GEN-LAST:event_BotonAñadirLocalActionPerformed

    private void BotonRestarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestarLocalActionPerformed
     miTablero.restaLocal();
     update();
    }//GEN-LAST:event_BotonRestarLocalActionPerformed

    private void BotonAñadirVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirVisitanteActionPerformed
     miTablero.sumaVisita();
     update();
    }//GEN-LAST:event_BotonAñadirVisitanteActionPerformed

    private void BotonRestarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestarVisitanteActionPerformed
     miTablero.restaVisita();
     update();
    }//GEN-LAST:event_BotonRestarVisitanteActionPerformed


    public Tablero update(){
        localValor.setText(""+miTablero.getLocal());
        visitanteValor.setText(""+miTablero.getVisitante());
        return miTablero;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAñadirLocal;
    private javax.swing.JToggleButton BotonAñadirVisitante;
    private javax.swing.JToggleButton BotonRestarLocal;
    private javax.swing.JToggleButton BotonRestarVisitante;
    private javax.swing.JToggleButton BtnReiniciar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JLabel localValor;
    private javax.swing.JLabel visitanteValor;
    // End of variables declaration//GEN-END:variables
}
